# Installing Apache on WebServers

- name: Installing Apache on Ubuntu Web-Servers
  hosts: ubuntu-web-servers
  remote_user: ubuntu
  become: yes

  tasks:
  - name: Updating Apt Cache
    apt:
      update_cache: yes

  - name: Installing Apache
    apt:
      name: apache2
      state: present

  - name: Starting Apache Service
    service:
      name: apache2
      state: started
      enabled: yes


- name: Installing Apache on Redhat Web-Servers
  hosts: redhat-web-servers
  remote_user: admin-user
  become: yes

  tasks:
  - name: Updating Yum Cache
    yum:
      update_cache: yes

  - name: Installing Apache
    yum:
      name: httpd
      state: present

  - name: Starting Apache Service
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Open HTTP port in firewalld (if enabled)
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_facts.services['firewalld'].state == 'running'